server:
  port: 8080

spring:
  application:
    name: producer-usuario-ms

  kafka:
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: topic-usuario-2
      bootstrap-servers: localhost:9092

    properties:
      auto:
        register:
          schemas: true
      schema:
        registry:
          url: http://127.0.0.1:8081
auto:
  create:
    topics:
      enable: true

topic:
  name:
    producer: topic-usuario-2
