server:
  port: 8055

app:
  kafka:
    producer:
      topic: ${APP_KAFKA_PRODUCER_TOPIC:solicitacao-transferencia}
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      #valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      valueSerializer: "org.apache.kafka.common.serialization.ByteArraySerializer"

      acks: 1
      compression-type: lz4
      properties:
        auto:
          register:
            schemas: true
    listener:
      missing-topics-fatal: ${KAFKA_FAIL_WHEN_MISSING_TOPICS:false}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    properties:
      schema:
        registry:
          url: ${SCHEMA_REGISTRY_URL:http://127.0.0.1:8081}